# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('audio_file', models.FileField(upload_to='SongsFolder')),
                ('emotionAttached', models.CharField(choices=[('fear', 'FEAR'), ('contempt', 'CONTEMPT'), ('anger', 'ANGER'), ('sadness', 'SADNESS'), ('surprise', 'SUPRIZE'), ('neutral', 'NEUTRAL'), ('disgust', 'DISGUST'), ('happiness', 'HAPPINESS')], default='green', max_length=6)),
            ],
        ),
    ]
