# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='emotionAttached',
            field=models.CharField(choices=[('fear', 'FEAR'), ('contempt', 'CONTEMPT'), ('anger', 'ANGER'), ('sadness', 'SADNESS'), ('surprise', 'SUPRIZE'), ('neutral', 'NEUTRAL'), ('disgust', 'DISGUST'), ('happiness', 'HAPPINESS')], default='green', max_length=20),
        ),
    ]
